### ISSUE TITLE
你好！我这面运行的时候出现的这种错误

### ISSUE THREAD

**Issue by 15230811395** [Nusture/FamilyFinancialManagementSystem#3]
<img width="1816" alt="image" src="https://user-images.githubusercontent.com/42630868/194740883-0205d798-a894-49f9-881d-c791e41fbb9b.png">

**Comment by Nusture** [comment]
不好意思这个项目已经很久没有维护了，我这边启动是正常的，是启动了其他的spark项目吗，或者检查一下相关依赖的版本试试
